controllers/form_controller.py
from flask import Blueprint, send_file, render_template
from services.form_service import get_forms, get_csv
import os
import csv
from dotenv import load_dotenv

# load environment variables
load_dotenv()
file_path = os.getenv("CSV_PATH")

form = Blueprint("form", __name__)


@form.route("/", methods=["GET"])
def get_forms():
    print("get_forms() called")
    get_forms()
    return "OK", 200


@form.route("/csv", methods=["GET"])
def get_csv_data():
    print("get_csv_data() called")
    data = get_csv()
    print("data:", data)
    return data, 200


@form.route("/csv/table", methods=["GET"])
def get_data_table():
    print("get_data_table() called")
    get_csv()
    with open(file_path) as csvfile:
        data = csv.reader(csvfile, delimiter=";")
        headers = next(data)
        return render_template("data.html", headers=headers, data=data)


@form.route("/csv/download", methods=["GET"])
def dl_csv_data():
    print("dl_csv_data() called")
    get_csv()
    path = "../" + file_path
    return send_file(
        path,
        as_attachment=True,
        download_name="data.csv",
        mimetype="text/csv",
    )

templates/data.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>Database datas</title>
		<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
		<style>
			body {
				font-family: Arial, sans-serif;
			}

			.button-container {
				margin-bottom: 10px;
			}

			.button-container a {
				margin-right: 10px;
			}

			button {
				padding: 8px 16px;
				font-size: 16px;
				border: none;
				border-radius: 4px;
				background-color: #4caf50;
				color: #fff;
				cursor: pointer;
			}

			button:hover {
				background-color: #45a049;
			}
		</style>
		<style>
			table {
				border-collapse: collapse;
				width: 100%;
				margin-bottom: 20px;
			}

			th,
			td {
				padding: 8px;
				text-align: left;
				border-bottom: 1px solid #ddd;
			}

			th {
				background-color: #f2f2f2;
				font-weight: bold;
			}
		</style>
	</head>
	<body>
		<h1>Database datas</h1>
		<table>
			<tr>
				{% for header in headers %}
				<th>{{ header }}</th>
				{% endfor %}
			</tr>
			{% for line in data %}
			<tr>
				{% for item in line %}
				<td>{{ item }}</td>
				{% endfor %}
			</tr>
			{% endfor %}
		</table>
		<a href="{{ url_for('form.dl_csv_data') }}">
			<button>Download Data</button>
		</a>
	</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>MY - Datas</title>
		<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
		<style>
			body {
				font-family: Arial, sans-serif;
			}

			.header {
				display: flex;
				align-items: center;
			}

			.header img {
				width: 50px;
				margin-right: 10px;
			}

			.button-container {
				margin-bottom: 10px;
			}

			.button-container a {
				margin-right: 10px;
			}

			button {
				padding: 8px 16px;
				font-size: 16px;
				border: none;
				border-radius: 4px;
				background-color: #4caf50;
				color: #fff;
				cursor: pointer;
			}

			button:hover {
				background-color: #45a049;
			}

			#logout {
				background-color: #f44336;
			}

			#logout:hover {
				background-color: #da190b;
			}
		</style>
	</head>
	<body>
		<div class="header">
			<img src="{{ url_for('static', filename='favicon.ico') }}" alt="Logo" />
			<h1>MY - Datas</h1>
		</div>
		<div class="button-container">
			<a href="{{ url_for('form.get_csv_data') }}">
				<button>View Raw Data</button>
			</a>
			<a href="{{ url_for('form.get_data_table') }}">
				<button>View Formatted Data</button>
			</a>
			<a href="{{ url_for('form.dl_csv_data') }}">
				<button>Download Data</button>
			</a>
			<a href="{{ url_for('logout') }}">
				<button id="logout">Logout</button>
			</a>
		</div>
	</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>MY - Connexion</title>
		<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />
		<style>
			body {
				font-family: Arial, sans-serif;
				background-color: #f5f5f5;
				margin: 0;
				padding: 0;
				display: flex;
				align-items: center;
				justify-content: center;
				min-height: 100vh;
			}

			.login-container {
				width: 400px;
				padding: 20px;
				background-color: #fff;
				border-radius: 4px;
				box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
			}

			.login-container h1 {
				text-align: center;
				margin-bottom: 20px;
			}

			.login-container form {
				display: flex;
				flex-direction: column;
			}

			.login-container label {
				margin-bottom: 8px;
			}

			.login-container input[type='text'],
			.login-container input[type='password'] {
				padding: 8px;
				border-radius: 4px;
				border: 1px solid #ccc;
				margin-bottom: 16px;
			}

			.login-container input[type='submit'] {
				padding: 8px 16px;
				font-size: 16px;
				border: none;
				border-radius: 4px;
				background-color: #4caf50;
				color: #fff;
				cursor: pointer;
			}

			.login-container input[type='submit']:hover {
				background-color: #45a049;
			}

			.error-message {
				color: red;
				margin: 16px 0;
			}
		</style>
	</head>
	<body>
		<div class="login-container">
			<h1>MY - Connection</h1>
			{% if incorrect %}
			<div class="error-message">Identifiants incorrects</div>
			{% endif %}
			<form method="POST" action="/login">
				<label for="username">Nom d'utilisateur</label>
				<input type="text" id="username" name="username" required /><br />
				<label for="password">Mot de passe</label>
				<input type="password" id="password" name="password" required /><br />
				<input type="submit" value="Se connecter" />
			</form>
		</div>
	</body>
</html>